//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administracion.Resources.textos", typeof(textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altitud .
        /// </summary>
        public static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas.
        /// </summary>
        public static string botonCit {
            get {
                return ResourceManager.GetString("botonCit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadro Mando.
        /// </summary>
        public static string botonDash {
            get {
                return ResourceManager.GetString("botonDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialidades.
        /// </summary>
        public static string botonEsp {
            get {
                return ResourceManager.GetString("botonEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        public static string botonIncio {
            get {
                return ResourceManager.GetString("botonIncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localizaciones.
        /// </summary>
        public static string botonLoc {
            get {
                return ResourceManager.GetString("botonLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medicamentos.
        /// </summary>
        public static string botonMed {
            get {
                return ResourceManager.GetString("botonMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        public static string botonObj {
            get {
                return ResourceManager.GetString("botonObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pacientes.
        /// </summary>
        public static string botonPac {
            get {
                return ResourceManager.GetString("botonPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan de cuidado.
        /// </summary>
        public static string botonPlan {
            get {
                return ResourceManager.GetString("botonPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posiciones.
        /// </summary>
        public static string botonPos {
            get {
                return ResourceManager.GetString("botonPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Médicos.
        /// </summary>
        public static string botonPrac {
            get {
                return ResourceManager.GetString("botonPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado por CroniCall.
        /// </summary>
        public static string copyRight {
            get {
                return ResourceManager.GetString("copyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string detalles {
            get {
                return ResourceManager.GetString("detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   Filtra los datos por cualquier campo.
        /// </summary>
        public static string filtrado {
            get {
                return ResourceManager.GetString("filtrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el usuario y la contraseña de administrador:.
        /// </summary>
        public static string formInicio {
            get {
                return ResourceManager.GetString("formInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de localizaciones por médicos y pacientes.
        /// </summary>
        public static string graficoCarga {
            get {
                return ResourceManager.GetString("graficoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pacientes por localización.
        /// </summary>
        public static string graficoPat {
            get {
                return ResourceManager.GetString("graficoPat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medicos por localización.
        /// </summary>
        public static string graficoPrac {
            get {
                return ResourceManager.GetString("graficoPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud .
        /// </summary>
        public static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de locations.
        /// </summary>
        public static string locList {
            get {
                return ResourceManager.GetString("locList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud .
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectarse.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña ....
        /// </summary>
        public static string placeHolderInicioPass {
            get {
                return ResourceManager.GetString("placeHolderInicioPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario ....
        /// </summary>
        public static string placeHolderInicioUsuario {
            get {
                return ResourceManager.GetString("placeHolderInicioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accede al dashboard.
        /// </summary>
        public static string subtituloInicio {
            get {
                return ResourceManager.GetString("subtituloInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso al login.
        /// </summary>
        public static string tituloInicio {
            get {
                return ResourceManager.GetString("tituloInicio", resourceCulture);
            }
        }
    }
}
